/// Flutter icons Casa_icon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Casa_icon
///      fonts:
///       - asset: fonts/Casa_icon.ttf
///
///
///
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';

class Casa_icon {
  Casa_icon._();

  static const _kFontFam = 'Casa_icon';

  static const IconData casa = IconData(0xe800, fontFamily: _kFontFam);
}
